### ISSUE TITLE
关于linux版本的问题

### ISSUE THREAD

**Issue by YuuLuo** [moxcomic/start#10]
使用的cpu为12900k cpu设置为24 lib已经替换过 进入对局报错segmentation fault
![K{5{MY(5%HNA1~V8IC@~5ZM](https://user-images.githubusercontent.com/69673808/191985740-24e7779f-b5b7-4769-819b-c6c32031f6f1.png)

lib替换为16后 错误信息如下
![image](https://user-images.githubusercontent.com/69673808/191986099-56e6ff38-e945-4a70-88c9-58c9cd3b6738.png)

**Comment by moxcomic** [comment]
可能内存不足
