### ISSUE TITLE
有关mahjong-helper的支持以及部分程序上的BUG

### ISSUE THREAD

**Issue by fbzr2007** [moxcomic/start#11]
在config.yaml中已经设置maj-helper为true
尝试在目录内新建replace文件夹并放入改名为code.js的code-zh.js，但出现程序闪退，且浏览器页面没有进入游戏，为空页面

无mahjong-helper的js可以正常启动游戏，但mahjong-helper程序无法识别

尝试仅使用该js并改名为scripts并打包无法被程序识别，卡在加载中

BUG类：
在设置中设置加载资源后不会出现对应架构文件夹目录及贴图数据，且替换资源类插件会正常加载

**Comment by moxcomic** [comment]
目前程序原生支持Mahjong-Helper实时对局部分，不过仅支持付费用户并且在AI模式下，该模式下只需要在主要设置中开启Mahjong-Helper即可，插件模式目前不太确定，现在原作者的js并不能使用，你得自己修改js
