### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by qertyuy** [moxcomic/start#7]
panic: fork/exec C:\Users\qqq\AppData\Local/Google/Chrome/Application/chrome.exe: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail. 
打开后出现这些，之后闪退

**Comment by moxcomic** [comment]
看起来似乎是chrome的错误，重新安装最新版本的chrome试试

**Comment by qertyuy** [comment]
旧版本的start可以启动chrome ，但是打不开国服雀魂的网页

**Comment by moxcomic** [comment]
因为第一次启动会让你选择服务器，第二次启动因为存在配置文件就不会让你选择，在`config.yaml`里将`server`改为`""`重新启动即可再次进行选择服务器`(注意只有在某些版本之后才会有game.maj-soul.net选项, 具体版本我记不清了)`
