### ISSUE TITLE
有没有快速启动的方法？

### ISSUE THREAD

**Issue by qylixin** [moxcomic/start#8]
每次打开游戏都需要先打开菜单，然后通过方向键选择“打开游戏”才会启动chrome，能否加个命令行的option，比如"--start"之类的，可以跳过菜单选择的步骤，直接启动chrome

**Comment by moxcomic** [comment]
暂时保留，后续版本会考虑

**Comment by moxcomic** [comment]
最新版`config.yaml`新增`quick_start`字段，设置为`true`即可
