### ISSUE TITLE
若干使用上的问题

### ISSUE THREAD

**Issue by user670** [moxcomic/start#9]
Windows 10 x64, Start 1.0.37. 国服 .com。

- 即使在config里写了chrome的位置，启动仍然是Edge。这是正常现象吗？
- 按照readme.md搞了个换牌面贴图的东西，不好使。试着用插件包（plugins repo）里的“一姬改希儿”插件，文字改了，图没变。这是正常现象吗？

**Comment by moxcomic** [comment]
1. 该功能在大版本更新时忘记进行修改, 后续更新会修复
2. 游戏图片是有缓存的, 缓存后即不会进行替换, 如果需要重置删除data文件夹即可

**Comment by user670** [comment]
> 游戏图片是有缓存的, 缓存后即不会进行替换, 如果需要重置删除data文件夹即可
清了caches和data，然后一姬还是一姬，没变希儿，所以是哪里不对:-/

**Comment by user670** [comment]
奇怪，有的东西改了，有的没改

我自己的改牌面改了局外牌面（例如玩家档案里的“最近大和”）但是没改局内牌面（怀疑是ui.png不管这里的贴图？）；一姬那个插件的图没变，只有文字变了（怀疑是插件的文件路径过时还是怎么？）

不知道问题出在插件还是别的地方.jpg

**Comment by moxcomic** [comment]
修改文件不对，需要自己测试
